### ISSUE TITLE
Binary name is not as in the readme when using go tools 

### ISSUE THREAD

**Issue by ghost** [kapilpau/go-mod-dependency-tree#2]
Nice tool !

When installing this tool using;

`go install github.com/kapilpau/go-mod-dependency-tree@v1.20`

or when using something like explained at: `https://stackoverflow.com/a/51397887/13170674`

The tool wont be installed as `go-tree` but as `go-mod-dependency-tree`

To me this was confusing when wanting to install your tool without using the make file. 

It might be a good idea to spend a small portion on how to install the tool as you intended it.

best regards

Xander

**Comment by kapilpau** [comment]
@XanderAtBackboneSystems it is intended that users download the binary from the GitHub release, rather than cloning the code. That should only be done when you wish to contribute to the codebase. I will add a note in the README to reflect that.
